### ISSUE TITLE
contradiction between paper and code for translation 

### ISSUE THREAD

**Issue by sksenthilkumar** [microsoft/View-Adaptive-Neural-Networks-for-Skeleton-based-Human-Action-Recognition#1]
In the published paper "View Adaptive Neural Network for High-Performance S-b HAR", the translation was described as subtracting the obtained translation values from the given point. But However in the implemented code (transform_rnn.py and transform_cnn.py), it looks like the translation values are added to given points. Is this a bug? or I Understood it wrong? 

Thanks in advance.

**Comment by shuidongliu** [comment]
The translation values are learned by the networks and the values can be positive or negative. Therefore,  it does not matter about using add or subtraction.
