### ISSUE TITLE
What is the reason to subtract the pixel values by 110? 

### ISSUE THREAD

**Issue by sksenthilkumar** [microsoft/View-Adaptive-Neural-Networks-for-Skeleton-based-Human-Action-Recognition#5]
https://github.com/microsoft/View-Adaptive-Neural-Networks-for-Skeleton-based-Human-Action-Recognition/blob/a2fdd94273dd452e1aa6fce18f0425be30daf7c3/data_cnn.py#L190

In the preprocessing step, all the pixel values of the pseudo image have been subtracted by 110. 
If we remove this function will it affect the performance?

**Comment by shuidongliu** [comment]
It is similar to the normalization with mean. In fact, you can ignore this step because of the little impact on the final result.
