### ISSUE TITLE
Regarding upgradation in python version

### ISSUE THREAD

**Issue by preksha12** [microsoft/View-Adaptive-Neural-Networks-for-Skeleton-based-Human-Action-Recognition#7]
Will this project work with python3.6. I have tried to run va-cnn.py according to readme file but got below mentioned error:-
<img width="584" alt="Screenshot 2020-04-07 at 12 52 41 AM" src="https://user-images.githubusercontent.com/9927293/78596859-1c024a00-786a-11ea-8d1e-24723e7bf6e6.png">

Thanks in advance.

**Comment by preksha12** [comment]
The issue is resolved now by using worker=0. As script.misc is deprecated so I used PIL numpy resize function.

**Comment by Anirudh257** [comment]
This problem is with scipy version. Use scipy=1.1.0.

**Comment by preksha12** [comment]
Yes the problem is solved now with scipy version

**Comment by preksha12** [comment]
> This problem is with scipy version. Use scipy=1.1.0.

Do you have any idea about theano part as I am getting attached  error in theano. 
<img width="578" alt="Screenshot 2020-04-16 at 10 08 43 PM" src="https://user-images.githubusercontent.com/9927293/79591976-ed506300-80f6-11ea-9e1a-c1c3a417fa71.png">

**Comment by Anirudh257** [comment]
Not sure but you can try installing theano in a condo environment and try running the program.
