### ISSUE TITLE
how can I visualize the 3D skeletal output from view adaptation sub-network  

### ISSUE THREAD

**Issue by Anupama-898** [microsoft/View-Adaptive-Neural-Networks-for-Skeleton-based-Human-Action-Recognition#9]
I want to visualize the resulting 3D skeletal from view adaptation sub-network as shown in paper too.Can anyone provide the code which can be used for the task.

**Comment by zgyangleo** [comment]
> I want to visualize the resulting 3D skeletal from view adaptation sub-network as shown in paper too.Can anyone provide the code which can be used for the task.
do you solve the visualization problem? i need your help. thanks.

**Comment by Anupama-898** [comment]
no I'm still not able to get the process to visualize them

**Comment by shuidongliu** [comment]
> no I'm still not able to get the process to visualize them

Sorry, I am busy these days. If you have any problem, you can email me with zpfcoury@gmail.com directly .  For visualization, you can use the code vis_3d_ske.py (https://drive.google.com/open?id=1x3K73PElUe0excRk6toIfj_JXDH2IkF9). The output of VA-subnetwork can be saved directly with the pretrained models (https://drive.google.com/open?id=12PfMRK2rSg0ndLbTVw-GelRrb2TVxazg)

**Comment by Anupama-898** [comment]
okay Thankyou for the reply.
